"""empty message

Revision ID: 697b847081bd
Revises: 
Create Date: 2021-01-20 22:29:45.365404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697b847081bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
